import { Cable, Eye, EyeOff, FolderKanban, KeyRound, LogIn, LogOut, MousePointer2, Settings2, ShieldCheck, Sparkles, Trash2, UserRound } from 'lucide-react'
import type { FormEvent } from 'react'
import type { AgentGraphMode } from '../core/agentic-graph'

export function AgentSettingsContent({ apiKey, autoApply, chatGPT, confirmDelete, credentialBusy, credentialMessage, graphMode, loading, onApiKeyChange, onAutoApplyChange, onConnectChatGPT, onDeleteApiKey, onDisconnectChatGPT, onGraphModeChange, onSaveApiKey, onShowApiKeyChange, onTestApiKey, settings, showApiKey }: { apiKey: string; autoApply: boolean; chatGPT?: ChatGPTSessionStatus; confirmDelete: boolean; credentialBusy: boolean; credentialMessage: string; graphMode: AgentGraphMode; loading: boolean; onApiKeyChange(value: string): void; onAutoApplyChange(value: boolean): void; onConnectChatGPT(): void; onDeleteApiKey(): void; onDisconnectChatGPT(): void; onGraphModeChange(value: AgentGraphMode): void; onSaveApiKey(event: FormEvent): void; onShowApiKeyChange(value: boolean): void; onTestApiKey(): void; settings?: OpenAISettingsStatus; showApiKey: boolean }) {
  return <div className="ask-labo-settings-content">
    <div className="ask-labo-intro"><strong>Atomic graph agent</strong><p>LABO inspects the typed card library, composes missing reusable cards when possible, wires the graph and returns an explicit plan.</p></div>
    <section aria-label="Agent apply mode" className="ask-labo-mode"><div><button aria-pressed={!autoApply} onClick={() => onAutoApplyChange(false)} type="button">Review</button><button aria-pressed={autoApply} onClick={() => onAutoApplyChange(true)} type="button">Auto apply</button></div><small>{autoApply ? 'Apply every locally valid operation immediately.' : 'Preview cards and elastics before applying.'}</small></section>
    <section aria-label="Agent graph scope" className="ask-labo-mode ask-labo-scope"><div><button aria-pressed={graphMode === 'extend'} disabled={loading} onClick={() => onGraphModeChange('extend')} type="button">Extend current</button><button aria-pressed={graphMode === 'parallel'} disabled={loading} onClick={() => onGraphModeChange('parallel')} type="button">New parallel</button></div><small>{graphMode === 'parallel' ? 'Keep the existing graph read-only and build beside it.' : 'Connect new cards to compatible free ports.'}</small></section>
    {window.labo?.runtime === 'electron' && <section className="ask-labo-key-settings ask-labo-chatgpt-settings">
      <div className="ask-labo-key-heading"><span><UserRound size={13} />ChatGPT account</span>{chatGPT?.connected && <b><span className="status-dot" />Connected</b>}</div>
      {chatGPT?.connected ? <><div className="ask-labo-key-status"><ShieldCheck size={16} /><span><strong>{chatGPT.email || 'ChatGPT account connected'}</strong><small>{chatGPT.planType ? `${chatGPT.planType} plan · ` : ''}Ask LABO uses this session by default. No API key is required.</small></span></div><div className="ask-labo-key-actions"><button disabled={credentialBusy} onClick={onDisconnectChatGPT} type="button"><LogOut size={12} />Disconnect ChatGPT</button></div></> : <div className="ask-labo-key-form"><p>Use your ChatGPT subscription for Ask LABO. Sign-in opens in your browser and Codex manages the session outside the renderer.</p><button disabled={credentialBusy} onClick={onConnectChatGPT} type="button"><LogIn size={12} />{credentialBusy ? 'Waiting for sign-in…' : chatGPT?.available === false ? 'Retry ChatGPT connection' : 'Continue with ChatGPT'}</button>{chatGPT?.error && <small>{chatGPT.error}</small>}</div>}
    </section>}
    <section className="ask-labo-key-settings">
      <div className="ask-labo-key-heading"><span><KeyRound size={13} />{window.labo?.runtime === 'electron' ? 'OpenAI API key · optional fallback' : 'OpenAI API key'}</span>{settings?.configured && <b><span className="status-dot" />Connected</b>}</div>
      {settings?.configured ? <><div className="ask-labo-key-status"><ShieldCheck size={16} /><span><strong>{settings.source === 'secure-storage' ? 'Stored securely for this user' : 'Provided by the app environment'}</strong><small>Secure storage is opened only when this provider is actually used.</small></span></div><div className="ask-labo-key-actions"><button disabled={credentialBusy} onClick={onTestApiKey} type="button">Test connection</button>{settings.source === 'secure-storage' && <button className={confirmDelete ? 'confirm-delete' : ''} disabled={credentialBusy} onClick={onDeleteApiKey} type="button"><Trash2 size={12} />{confirmDelete ? 'Confirm removal' : 'Remove key'}</button>}{window.labo?.runtime === 'web' && <a href="/dashboard/settings" target="_top">Manage account</a>}</div></> : settings?.authRequired ? <div className="ask-labo-key-form"><p>Everything except Ask LABO works without an account.</p><a className="ask-labo-sign-in" href="/auth/signin?callbackUrl=%2Flabo-ai%2Flive" target="_top"><ShieldCheck size={12} />Sign in to use the agent</a></div> : <form className="ask-labo-key-form" onSubmit={onSaveApiKey}><p>No API key configured for this user.</p><small>Disabled by default. The system keychain is contacted only after you submit a key here.</small><label htmlFor="openai-api-key">OpenAI API key</label><div><input autoComplete="off" id="openai-api-key" onChange={(event) => onApiKeyChange(event.target.value)} placeholder="sk-…" type={showApiKey ? 'text' : 'password'} value={apiKey} /><button aria-label={showApiKey ? 'Hide API key' : 'Show API key'} onClick={() => onShowApiKeyChange(!showApiKey)} type="button">{showApiKey ? <EyeOff size={13} /> : <Eye size={13} />}</button></div><button disabled={credentialBusy || apiKey.trim().length < 20 || settings?.encryptionAvailable === false} type="submit"><ShieldCheck size={12} />{credentialBusy ? 'Saving…' : 'Save and verify key'}</button>{settings?.encryptionAvailable === false && <small>Secure storage requires the LABO AI desktop app and an available system keychain.</small>}</form>}
      {credentialMessage && <p className="ask-labo-key-message">{credentialMessage}</p>}
    </section>
  </div>
}

export function StudioEditingTips() {
  return <div className="ask-labo-tips">
    <article><span><MousePointer2 size={14} />Select & delete</span><strong>Delete several cards or a full graph</strong><p>Switch to <b>Edit cards</b>, then drag on empty canvas around the cards. Hold Shift, Cmd or Ctrl while clicking to adjust the selection, then choose <b>Delete selection</b>. Connected elastics are removed with the cards.</p></article>
    <article><span><Settings2 size={14} />Edit a card</span><strong>Open card settings</strong><p>In <b>Edit cards</b>, click a card to open its settings. You can also right-click a card for the Edit and Delete actions.</p></article>
    <article><span><Cable size={14} />Add & wire</span><strong>Compose manually</strong><p>Use <b>Add blocks</b>, click a card to place it automatically or drag it onto the canvas, then drag between compatible typed plugs.</p></article>
    <article><span><FolderKanban size={14} />Save & compare</span><strong>Keep each architecture reusable</strong><p>Open <b>Settings → Workspaces</b> to name, save, reset or place complete presets side by side.</p></article>
    <article><span><Sparkles size={14} />Ask LABO</span><strong>Build with natural language</strong><p>Describe the architecture in the footer prompt. Configure review, auto-apply and parallel mode under <b>Settings → Agent</b>.</p></article>
  </div>
}
