import type { ArchitectureGraph } from './ir'

export const visionTransformerPreset: ArchitectureGraph = {
  id: 'vision-transformer',
  name: 'Vision Transformer · Patch Encoder',
  architecture: 'custom',
  config: { hiddenSize: 512, queryHeads: 8, keyValueHeads: 8, headDim: 64 },
  contracts: { causal: false, preservesGqaAtZeroGate: false, sdpaCompatible: true, contextualValue: true },
  nodes: [
    { id: 'image-patches', kind: 'input', label: 'Image patch features', role: 'hidden', position: { x: 180, y: 35 } },
    { id: 'patch-projection', kind: 'semantic', atomId: 'vision-patch-projection', label: 'Vision patch projection', role: 'hidden', position: { x: 180, y: 145 }, attributes: { bias: true } },
    { id: 'vision-type', kind: 'semantic', atomId: 'modality-type-embedding', label: 'Vision type embedding', role: 'hidden', position: { x: 180, y: 255 }, attributes: { initialScale: 0.02 } },
    { id: 'vision-norm', kind: 'semantic', atomId: 'rms-norm', label: 'Pre-attention RMSNorm', role: 'hidden', position: { x: 180, y: 365 }, attributes: { epsilon: 1e-6 } },
    { id: 'vision-qkv', kind: 'semantic', atomId: 'qkv-projection', label: 'Vision QKV projection', role: 'output', position: { x: 180, y: 475 }, attributes: { bias: true, fused: true } },
    { id: 'vision-heads', kind: 'semantic', atomId: 'attention-head-layout', label: '8 vision attention heads', role: 'output', position: { x: 180, y: 595 }, attributes: { queryHeads: 8, keyValueHeads: 8, headDim: 64 } },
    { id: 'vision-attention', kind: 'semantic', atomId: 'noncausal-sdpa', label: 'Bidirectional patch attention', role: 'attention', position: { x: 180, y: 715 }, attributes: { dropout: 0 } },
    { id: 'vision-merge', kind: 'semantic', atomId: 'merge-attention-heads', label: 'Merge vision heads', role: 'hidden', position: { x: 180, y: 825 } },
    { id: 'vision-output', kind: 'semantic', atomId: 'attention-output-projection', label: 'Vision output projection', role: 'hidden', position: { x: 180, y: 935 }, attributes: { bias: true } },
    { id: 'vision-residual', kind: 'semantic', atomId: 'residual-add', label: 'Vision residual add', role: 'hidden', position: { x: 180, y: 1045 } },
    { id: 'vision-mlp', kind: 'semantic', atomId: 'residual-gelu-mlp', label: 'Vision residual GELU MLP', role: 'hidden', position: { x: 180, y: 1155 }, attributes: { intermediateSize: 2048, bias: true } },
    { id: 'vision-latents', kind: 'semantic', atomId: 'image-latent-decoder', label: 'Image latent output', role: 'hidden', position: { x: 180, y: 1265 }, attributes: { bias: true } },
  ],
  edges: [
    { id: 'patches-project', source: 'image-patches', sourcePort: 'hidden', target: 'patch-projection', targetPort: 'hidden' },
    { id: 'project-type', source: 'patch-projection', sourcePort: 'output', target: 'vision-type', targetPort: 'hidden' },
    { id: 'type-norm', source: 'vision-type', sourcePort: 'output', target: 'vision-norm', targetPort: 'hidden' },
    { id: 'norm-qkv', source: 'vision-norm', sourcePort: 'output', target: 'vision-qkv', targetPort: 'hidden' },
    { id: 'qkv-q-heads', source: 'vision-qkv', sourcePort: 'q', target: 'vision-heads', targetPort: 'q' },
    { id: 'qkv-k-heads', source: 'vision-qkv', sourcePort: 'k', target: 'vision-heads', targetPort: 'k' },
    { id: 'qkv-v-heads', source: 'vision-qkv', sourcePort: 'v', target: 'vision-heads', targetPort: 'v' },
    { id: 'heads-q-attention', source: 'vision-heads', sourcePort: 'qHeads', target: 'vision-attention', targetPort: 'q' },
    { id: 'heads-k-attention', source: 'vision-heads', sourcePort: 'kHeads', target: 'vision-attention', targetPort: 'k' },
    { id: 'heads-v-attention', source: 'vision-heads', sourcePort: 'vHeads', target: 'vision-attention', targetPort: 'v' },
    { id: 'attention-merge', source: 'vision-attention', sourcePort: 'output', target: 'vision-merge', targetPort: 'attention' },
    { id: 'merge-output', source: 'vision-merge', sourcePort: 'output', target: 'vision-output', targetPort: 'hidden' },
    { id: 'type-residual', source: 'vision-type', sourcePort: 'output', target: 'vision-residual', targetPort: 'residual' },
    { id: 'output-residual', source: 'vision-output', sourcePort: 'output', target: 'vision-residual', targetPort: 'branch' },
    { id: 'residual-mlp', source: 'vision-residual', sourcePort: 'output', target: 'vision-mlp', targetPort: 'hidden' },
    { id: 'mlp-latents', source: 'vision-mlp', sourcePort: 'output', target: 'vision-latents', targetPort: 'hidden' },
  ],
}

export const multimodalImageEditorPreset: ArchitectureGraph = {
  id: 'multimodal-image-editor',
  name: 'Multimodal Image Editor · Text + Vision',
  architecture: 'custom',
  config: { hiddenSize: 512, queryHeads: 8, keyValueHeads: 8, headDim: 64 },
  contracts: { causal: false, preservesGqaAtZeroGate: false, sdpaCompatible: true, contextualValue: true },
  nodes: [
    { id: 'edit-image', kind: 'input', label: 'Source image patches', role: 'hidden', position: { x: 35, y: 35 } },
    { id: 'edit-tokens', kind: 'input', label: 'Edit prompt Token IDs', role: 'token-ids', position: { x: 325, y: 35 } },
    { id: 'edit-vision', kind: 'semantic', atomId: 'vision-patch-projection', label: 'Image patch encoder', role: 'hidden', position: { x: 35, y: 155 }, attributes: { bias: true } },
    { id: 'edit-text', kind: 'semantic', atomId: 'token-embedding', label: 'Edit prompt embedding', role: 'hidden', position: { x: 325, y: 155 }, attributes: { vocabSize: 32000, hiddenSize: 512 } },
    { id: 'edit-vision-type', kind: 'semantic', atomId: 'modality-type-embedding', label: 'Vision modality embedding', role: 'hidden', position: { x: 35, y: 275 }, attributes: { initialScale: 0.02 } },
    { id: 'edit-text-projection', kind: 'semantic', atomId: 'conditioning-projection', label: 'Text conditioning projection', role: 'hidden', position: { x: 325, y: 275 }, attributes: { bias: false } },
    { id: 'edit-fusion', kind: 'semantic', atomId: 'adaptive-conditioning', label: 'Adaptive text-image conditioning', role: 'hidden', position: { x: 180, y: 405 }, attributes: { bias: true } },
    { id: 'edit-norm', kind: 'semantic', atomId: 'rms-norm', label: 'Multimodal RMSNorm', role: 'hidden', position: { x: 180, y: 515 }, attributes: { epsilon: 1e-6 } },
    { id: 'edit-qkv', kind: 'semantic', atomId: 'qkv-projection', label: 'Multimodal QKV projection', role: 'output', position: { x: 180, y: 625 }, attributes: { bias: true, fused: true } },
    { id: 'edit-heads', kind: 'semantic', atomId: 'attention-head-layout', label: '8 multimodal heads', role: 'output', position: { x: 180, y: 745 }, attributes: { queryHeads: 8, keyValueHeads: 8, headDim: 64 } },
    { id: 'edit-attention', kind: 'semantic', atomId: 'noncausal-sdpa', label: 'Text-image attention', role: 'attention', position: { x: 180, y: 865 }, attributes: { dropout: 0 } },
    { id: 'edit-merge', kind: 'semantic', atomId: 'merge-attention-heads', label: 'Merge multimodal heads', role: 'hidden', position: { x: 180, y: 975 } },
    { id: 'edit-output', kind: 'semantic', atomId: 'attention-output-projection', label: 'Multimodal output projection', role: 'hidden', position: { x: 180, y: 1085 }, attributes: { bias: true } },
    { id: 'edit-residual', kind: 'semantic', atomId: 'residual-add', label: 'Conditioning residual add', role: 'hidden', position: { x: 180, y: 1195 } },
    { id: 'edit-denoiser', kind: 'semantic', atomId: 'latent-denoiser', label: 'Residual image denoiser', role: 'hidden', position: { x: 180, y: 1305 }, attributes: { intermediateSize: 2048, bias: true } },
    { id: 'edit-decoder', kind: 'semantic', atomId: 'image-latent-decoder', label: 'Edited image latent decoder', role: 'hidden', position: { x: 180, y: 1415 }, attributes: { bias: true } },
  ],
  edges: [
    { id: 'image-vision', source: 'edit-image', sourcePort: 'hidden', target: 'edit-vision', targetPort: 'hidden' },
    { id: 'tokens-text', source: 'edit-tokens', sourcePort: 'tokenIds', target: 'edit-text', targetPort: 'tokenIds' },
    { id: 'vision-type', source: 'edit-vision', sourcePort: 'output', target: 'edit-vision-type', targetPort: 'hidden' },
    { id: 'text-projection', source: 'edit-text', sourcePort: 'output', target: 'edit-text-projection', targetPort: 'hidden' },
    { id: 'vision-fusion', source: 'edit-vision-type', sourcePort: 'output', target: 'edit-fusion', targetPort: 'content' },
    { id: 'text-fusion', source: 'edit-text-projection', sourcePort: 'output', target: 'edit-fusion', targetPort: 'conditioning' },
    { id: 'fusion-norm', source: 'edit-fusion', sourcePort: 'output', target: 'edit-norm', targetPort: 'hidden' },
    { id: 'norm-qkv', source: 'edit-norm', sourcePort: 'output', target: 'edit-qkv', targetPort: 'hidden' },
    { id: 'qkv-q-heads', source: 'edit-qkv', sourcePort: 'q', target: 'edit-heads', targetPort: 'q' },
    { id: 'qkv-k-heads', source: 'edit-qkv', sourcePort: 'k', target: 'edit-heads', targetPort: 'k' },
    { id: 'qkv-v-heads', source: 'edit-qkv', sourcePort: 'v', target: 'edit-heads', targetPort: 'v' },
    { id: 'heads-q-attention', source: 'edit-heads', sourcePort: 'qHeads', target: 'edit-attention', targetPort: 'q' },
    { id: 'heads-k-attention', source: 'edit-heads', sourcePort: 'kHeads', target: 'edit-attention', targetPort: 'k' },
    { id: 'heads-v-attention', source: 'edit-heads', sourcePort: 'vHeads', target: 'edit-attention', targetPort: 'v' },
    { id: 'attention-merge', source: 'edit-attention', sourcePort: 'output', target: 'edit-merge', targetPort: 'attention' },
    { id: 'merge-output', source: 'edit-merge', sourcePort: 'output', target: 'edit-output', targetPort: 'hidden' },
    { id: 'fusion-residual', source: 'edit-fusion', sourcePort: 'output', target: 'edit-residual', targetPort: 'residual' },
    { id: 'output-residual', source: 'edit-output', sourcePort: 'output', target: 'edit-residual', targetPort: 'branch' },
    { id: 'residual-denoiser', source: 'edit-residual', sourcePort: 'output', target: 'edit-denoiser', targetPort: 'hidden' },
    { id: 'denoiser-decoder', source: 'edit-denoiser', sourcePort: 'output', target: 'edit-decoder', targetPort: 'hidden' },
  ],
}

export const videoTransformerPreset: ArchitectureGraph = {
  id: 'video-transformer',
  name: 'Video Transformer · Spatial + Temporal',
  architecture: 'custom',
  config: { hiddenSize: 512, queryHeads: 8, keyValueHeads: 8, headDim: 64 },
  contracts: { causal: false, preservesGqaAtZeroGate: false, sdpaCompatible: true, contextualValue: true },
  nodes: [
    { id: 'video-patches', kind: 'input', label: 'Video frame patch features', role: 'hidden', position: { x: 180, y: 35 } },
    { id: 'video-spatial', kind: 'semantic', atomId: 'vision-patch-projection', label: 'Spatial patch projection', role: 'hidden', position: { x: 180, y: 145 }, attributes: { bias: true } },
    { id: 'video-temporal', kind: 'semantic', atomId: 'temporal-depthwise-convolution', label: 'Temporal frame mixing', role: 'hidden', position: { x: 180, y: 255 }, attributes: { kernelSize: 3 } },
    { id: 'video-type', kind: 'semantic', atomId: 'modality-type-embedding', label: 'Video modality embedding', role: 'hidden', position: { x: 180, y: 365 }, attributes: { initialScale: 0.02 } },
    { id: 'video-norm', kind: 'semantic', atomId: 'rms-norm', label: 'Video RMSNorm', role: 'hidden', position: { x: 180, y: 475 }, attributes: { epsilon: 1e-6 } },
    { id: 'video-qkv', kind: 'semantic', atomId: 'qkv-projection', label: 'Spatiotemporal QKV', role: 'output', position: { x: 180, y: 585 }, attributes: { bias: true, fused: true } },
    { id: 'video-heads', kind: 'semantic', atomId: 'attention-head-layout', label: '8 video attention heads', role: 'output', position: { x: 180, y: 705 }, attributes: { queryHeads: 8, keyValueHeads: 8, headDim: 64 } },
    { id: 'video-attention', kind: 'semantic', atomId: 'noncausal-sdpa', label: 'Spatiotemporal attention', role: 'attention', position: { x: 180, y: 825 }, attributes: { dropout: 0 } },
    { id: 'video-merge', kind: 'semantic', atomId: 'merge-attention-heads', label: 'Merge video heads', role: 'hidden', position: { x: 180, y: 935 } },
    { id: 'video-output', kind: 'semantic', atomId: 'attention-output-projection', label: 'Video output projection', role: 'hidden', position: { x: 180, y: 1045 }, attributes: { bias: true } },
    { id: 'video-residual', kind: 'semantic', atomId: 'residual-add', label: 'Video residual add', role: 'hidden', position: { x: 180, y: 1155 } },
    { id: 'video-denoiser', kind: 'semantic', atomId: 'latent-denoiser', label: 'Temporal latent denoiser', role: 'hidden', position: { x: 180, y: 1265 }, attributes: { intermediateSize: 2048, bias: true } },
    { id: 'video-decoder', kind: 'semantic', atomId: 'video-latent-decoder', label: 'Video frame decoder', role: 'hidden', position: { x: 180, y: 1375 }, attributes: { bias: true } },
  ],
  edges: [
    { id: 'patches-spatial', source: 'video-patches', sourcePort: 'hidden', target: 'video-spatial', targetPort: 'hidden' },
    { id: 'spatial-temporal', source: 'video-spatial', sourcePort: 'output', target: 'video-temporal', targetPort: 'hidden' },
    { id: 'temporal-type', source: 'video-temporal', sourcePort: 'output', target: 'video-type', targetPort: 'hidden' },
    { id: 'type-norm', source: 'video-type', sourcePort: 'output', target: 'video-norm', targetPort: 'hidden' },
    { id: 'norm-qkv', source: 'video-norm', sourcePort: 'output', target: 'video-qkv', targetPort: 'hidden' },
    { id: 'qkv-q-heads', source: 'video-qkv', sourcePort: 'q', target: 'video-heads', targetPort: 'q' },
    { id: 'qkv-k-heads', source: 'video-qkv', sourcePort: 'k', target: 'video-heads', targetPort: 'k' },
    { id: 'qkv-v-heads', source: 'video-qkv', sourcePort: 'v', target: 'video-heads', targetPort: 'v' },
    { id: 'heads-q-attention', source: 'video-heads', sourcePort: 'qHeads', target: 'video-attention', targetPort: 'q' },
    { id: 'heads-k-attention', source: 'video-heads', sourcePort: 'kHeads', target: 'video-attention', targetPort: 'k' },
    { id: 'heads-v-attention', source: 'video-heads', sourcePort: 'vHeads', target: 'video-attention', targetPort: 'v' },
    { id: 'attention-merge', source: 'video-attention', sourcePort: 'output', target: 'video-merge', targetPort: 'attention' },
    { id: 'merge-output', source: 'video-merge', sourcePort: 'output', target: 'video-output', targetPort: 'hidden' },
    { id: 'type-residual', source: 'video-type', sourcePort: 'output', target: 'video-residual', targetPort: 'residual' },
    { id: 'output-residual', source: 'video-output', sourcePort: 'output', target: 'video-residual', targetPort: 'branch' },
    { id: 'residual-denoiser', source: 'video-residual', sourcePort: 'output', target: 'video-denoiser', targetPort: 'hidden' },
    { id: 'denoiser-decoder', source: 'video-denoiser', sourcePort: 'output', target: 'video-decoder', targetPort: 'hidden' },
  ],
}
